version: '3.8'

services:
  postgresql-database:
    image: postgres:14.2-alpine
    environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=Server123*
        #- POSTGRES_INITDB_ARGS=--encoding=UTF-8 // no esta los idiomas en alpine y solo tiene UTF8
        - LC_COLLATE=es_ES.UTF-8
        - LC_CTYPE=es_ES.UTF-8
        - POSTGRES_DB=PadronDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  pgadmin:
  postgresql-data:
      