// <auto-generated />
using ApiRestSunat.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiRestSunat.EntityFramework.Migrations
{
    [DbContext(typeof(ApiRestDbContext))]
    partial class ApiRestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Padron_sunat_10", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicion")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("Id");

                    b.ToTable("Padron_sunat_10");
                });

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Padron_sunat_15", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicion")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("Id");

                    b.ToTable("Padron_sunat_15");
                });

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Padron_sunat_17", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicion")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.HasKey("Id");

                    b.ToTable("Padron_sunat_17");
                });

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Padron_sunat_20", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDeZona")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Condicion")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Departamento")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Estado")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Interior")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Kilometro")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Lote")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("Manzana")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("NombreDeVia")
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("Numero")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("VARCHAR(200)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(11)
                        .HasColumnType("VARCHAR(11)");

                    b.Property<string>("TipoDeVia")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<string>("TipoDeZona")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Ubigeo")
                        .HasColumnType("VARCHAR(10)");

                    b.HasKey("Id");

                    b.ToTable("Padron_sunat_20");
                });

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Padron_sunat_dni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dni")
                        .HasColumnType("text");

                    b.Property<string>("Nombres")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Padron_sunat_dni");
                });

            modelBuilder.Entity("ApiRestSunat.Domain.Models.Ubigeo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Altitud")
                        .HasColumnType("integer");

                    b.Property<string>("Departamento")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Departamento_inei")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Distrito")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Fips")
                        .HasColumnType("VARCHAR(4)");

                    b.Property<string>("Iso_3166_2")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<decimal>("Latitud")
                        .HasColumnType("numeric(14,8)");

                    b.Property<decimal>("Longitud")
                        .HasColumnType("numeric(14,8)");

                    b.Property<string>("Macroregion_inei")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Macroregion_minsa")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Provincia")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Provincia_inei")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("Region")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("Superficie")
                        .HasColumnType("numeric(11,2)");

                    b.Property<string>("Ubigeo_inei")
                        .HasColumnType("VARCHAR(6)");

                    b.Property<string>("Ubigeo_reniec")
                        .HasColumnType("VARCHAR(6)");

                    b.HasKey("Id");

                    b.ToTable("Ubigeo");
                });
#pragma warning restore 612, 618
        }
    }
}
